#ifndef __SimGOSymulatorGO__
#define __SimGOSymulatorGO__

/**
@file
Subclass of SymulatorGO, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include

/** Implementing SymulatorGO */
class SimGOSymulatorGO : public SymulatorGO
{
	public:
		/** Constructor */
		SimGOSymulatorGO( wxWindow* parent );
	//// end generated class members




};

#endif // __SimGOSymulatorGO__
